version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jewelry_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - jewelry_network
    depends_on:
      - mysql
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: jewelry_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/ssl/:/etc/ssl/certs
    networks:
      - jewelry_network
    depends_on:
      - app

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: jewelry_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jewelry_platform
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: jewelry_user
      MYSQL_PASSWORD: jewelry_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - jewelry_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: jewelry_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - jewelry_network

  # Vite Development Server
  vite:
    build:
      context: .
      dockerfile: docker/vite/Dockerfile
    container_name: jewelry_vite
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    working_dir: /var/www
    command: npm run dev
    networks:
      - jewelry_network
    depends_on:
      - app

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  jewelry_network:
    driver: bridge